AWSTemplateFormatVersion: "2010-09-09"
Description: Adding Setting Of ACM For LenSentNextjsApp

Resources:
  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ACM
      DefaultActions:
        - TargetGroupArn: !ImportValue TargetGroupName
          Type: forward
      LoadBalancerArn: !ImportValue InternetALBName
  ACM:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !ImportValue DomainName
      DomainValidationOptions:
        - DomainName: !ImportValue DomainName
          HostedZoneId: !ImportValue HostedZoneId
      ValidationMethod: DNS
